databases:
  - name: legitedu1
    plan: free
    databaseName: legitedu1
    user: legitedu1

services:
  - type: web
    plan: free
    name: legitedu1
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: legitedu1db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4