databases:
  - name: legitedu
    plan: free
    databaseName: legitedu
    user: legitedu

services:
  - type: web
    plan: free
    name: legitedu1
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn eduweb.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: legitedu
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4